Repository Limeload/mcp-for-database, pull requests merged in 2025-10, with the labels that each got.

#45 worked on ux/ui
  .eslintrc.json
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
  app/api/db/[query]/route.ts
  app/components/DbConsole.tsx
  app/globals.css
  app/learn-more/page.tsx
  app/page.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: good first issue, hacktoberfest, type: frontend, type: ux/ui, priority: High

#50 Potential fix for code scanning alert no. 4: Workflow does not contain permissions
  .github/workflows/ci.yml
Labels: bug, good first issue, hacktoberfest, priority: High

#49 Potential fix for code scanning alert no. 8: Workflow does not contain permissions
  .github/workflows/security.yml
Labels: bug, good first issue, hacktoberfest, priority: High

#58 feat: add loading states to database console
  app/components/DbConsole.tsx
Labels: hacktoberfest, hactoberfest-accepted

#52 feat: add query export functionality (#22)
  app/components/DbConsole.tsx
  app/utils/exportUtils.ts
Labels: hacktoberfest, hactoberfest-accepted
